on:
  push:
  workflow_dispatch:

name: smwbuild

jobs:
  smwbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build Docker 
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 30
    - run: |
        set -x
        bash smw-build.sh
